experiment_name: "resunet_nobuffer_finetune"
n_models: 2

model_params:
  dropout_rate: 0.0

train_kwargs:
  epochs: 2000
  early_stopping_epochs: 1
  batch_size: 16
  learning_rate: 0.0001
  loss_fn: "custom_offset_entropy_loss"
  uncertainty_dir: "experimentos_deforestation/out_resunet_nobuffer/uncertainty/"
  uncertainty_metric: "StdDev"

fine_tune_kwargs:
  fine_tune_at: 31
  learning_rate: 0.00001
  epochs: 2000
  early_stopping_epochs: 1
  batch_size: 16
  loss_fn: "masked_cce"
  uncertainty_dir: null
  uncertainty_metric: "StdDev"
  
uncertainty_kwargs:
  metric: "StdDev"