# -*- coding: utf-8 -*-
"""
Created on Wed Aug 19 15:50:25 2026

@author: Marcel
"""

# %% Import Libraries

import pandas as pd
from pathlib import Path

# %%

class CrossExperimentReporter:
    """Scans a base directory for experiment outputs and aggregates them into master reports."""
    
    def __init__(self, base_exp_dir: str):
        self.base_exp_dir = Path(base_exp_dir)
        
        if not self.base_exp_dir.exists():
            raise FileNotFoundError(f"Base directory {self.base_exp_dir} does not exist.")
            
    def _discover_experiment_dirs(self) -> list[Path]:
        """Finds all directories starting with 'out_' inside the base directory."""
        return [
            d for d in self.base_exp_dir.iterdir() 
            if d.is_dir() and d.name.startswith('out_')
        ]
    
    def generate_master_summaries(self, buffers_px: list[int] = None, export_csv: bool = True,
                                  export_excel: bool = True) -> dict[int, pd.DataFrame]:
        """Iterates through all provided buffers and orchestrates summary generation."""
        buffers_px = buffers_px or [0]
        master_tables = {}
        
        # 1. Generate all tables dynamically
        for buffer_px in buffers_px:
            master_tables[buffer_px] = self._generate_single_buffer_summary(buffer_px, export_csv)
            
        # 2. Export the consolidated multi-tab Excel file
        if export_excel and any(not df.empty for df in master_tables.values()):
            self._export_to_excel(master_tables)
            
        return master_tables
    
    def _generate_single_buffer_summary(self, buffer_px: int, export_csv: bool) -> pd.DataFrame:
        """Private helper: Combines mosaic summaries for a specific buffer into one DataFrame."""
        print(f"\n=== Generating Master Global Summary ({buffer_px}px buffer) ===")
        
        all_experiment_dfs = []
        experiment_dirs = self._discover_experiment_dirs()
        
        if not experiment_dirs:
            print(f"  [!] No directories starting with 'out_' found in {self.base_exp_dir}.")
            return pd.DataFrame()
        
        for exp_dir in experiment_dirs:
            # Reconstruct the experiment name by stripping the 'out_' prefix
            experiment_name = exp_dir.name.replace('out_', '', 1)
            
            # Locate the summary CSV generated by the MetricsReporter
            summary_csv_path = exp_dir / f'ensemble_mosaic_summary_{buffer_px}px.csv'
            
            if not summary_csv_path.exists():
                print(f"  [!] Missing summary for {experiment_name} at {buffer_px}px. Skipping.")
                continue
                
            # Load the experiment's summary table
            df = pd.read_csv(summary_csv_path)
            
            # Insert a new column at the very beginning to identify the experiment
            df.insert(0, 'Experiment', experiment_name)
            
            all_experiment_dfs.append(df)
            
        if not all_experiment_dfs:
            print(f"  [!] No valid summaries found for {buffer_px}px. Aborted.")
            return pd.DataFrame()
        
        # Stitch all the dataframes together vertically
        master_df = pd.concat(all_experiment_dfs, ignore_index=True)
    
        if export_csv:
            output_path = self.base_exp_dir / f'master_experiment_summary_{buffer_px}px.csv'
            master_df.to_csv(output_path, index=False)
            print(f"Master summary successfully exported to: {output_path.name}")
            
        return master_df
    
    def _export_to_excel(self, master_tables: dict[int, pd.DataFrame]):
        """Private helper: Maps a dictionary of DataFrames to separate sheets in a single Excel file."""
        output_path = self.base_exp_dir / 'master_experiment_summaries.xlsx'
        print("\n=== Exporting Multi-Tabbed Excel Summary ===")
        
        with pd.ExcelWriter(output_path, engine='openpyxl') as writer:
            for buffer_px, df in master_tables.items():
                if not df.empty:
                    # Name the sheet dynamically based on the buffer size
                    sheet_name = f"{buffer_px}px_Buffer"
                    df.to_excel(writer, sheet_name=sheet_name, index=False)