#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Sep  1 15:52:22 2026

@author: rotunno
"""

# %% Imports

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
from typing import Union

# %% Figure Generator

class FigureGenerator:
    """
    Generates publication-quality 2x4 figures for GRSL by dynamically
    identifying and loading the median model's predictions based on the master summary CSV.
    """
    def __init__(self, base_exp_dir: Union[str, Path], master_csv_path: Union[str, Path]):
        self.base_exp_dir = Path(base_exp_dir)
        
        # Load the master summary generated by CrossExperimentReporter
        self.summary_df = pd.read_csv(master_csv_path)
        
        self.x_path = self.base_exp_dir / 'x_dir' / 'x_test.npy'
        self.y_path = self.base_exp_dir / 'y_dir' / 'y_test.npy'
        
        # Map the exact GRSL display titles to your experiment names.
        # Note: CrossExperimentReporter strips 'out_' from the directory name 
        # when saving to the CSV, so we use the stripped names here.
        self.experiments = {
            'Standard CE': 'cross_standard',
            'U-CE': 'cross_uncertainty',
            'Dice Loss': 'dice_standard',
            'U-Dice': 'dice_uncertainty',
            'Combo Loss': 'combo_standard',
            'Combo-UCE': 'combo_uncertainty'
        }
        
    def _get_median_model_id(self, exp_name: str, metric_col: str = 'relaxed_f1', model_col: str = 'Model') -> str:
        """
        Filters the CSV for a specific experiment and calculates which 
        individual model ('m_0' to 'm_4') represents the median performance.
        """
        # 1. Isolate the specific experiment
        df_exp = self.summary_df[self.summary_df['Experimento'] == exp_name].copy()
        
        # 2. Filter out aggregated rows (Mean, Median, Std) to leave only the 5 ensemble models.
        # Adjust 'm_' if your models are named differently in the CSV.
        df_models = df_exp[df_exp[model_col].str.startswith('m_')]
        
        if df_models.empty:
            raise ValueError(f"No individual models found for experiment '{exp_name}' in the CSV.")
            
        # 3. Sort by the evaluation metric to locate the median
        df_sorted = df_models.sort_values(by=metric_col).reset_index(drop=True)
        
        # 4. Extract the ID of the median model
        median_idx = len(df_sorted) // 2
        median_model_id = df_sorted.loc[median_idx, model_col]
        
        return median_model_id
    
    def generate_figure(self, patch_idx: int, save_path: Union[str, Path] = 'grsl_figure.pdf'):
        """Generates and saves the 2x4 grid."""
        # Initialize a 2x4 grid explicitly sized for journal single-column limits
        fig, axes = plt.subplots(2, 4, figsize=(12, 6))
        axes = axes.flatten()
        
        # 1. Load Input and Ground Truth (Memory mapped for efficiency)
        x_patch = np.load(self.x_path, mmap_mode='r')[patch_idx].astype(np.float32) # For compatibility with matplotlib
        y_patch = np.load(self.y_path, mmap_mode='r')[patch_idx]
        
        # Plot Input & GT
        axes[0].imshow(x_patch, cmap='gray')
        axes[0].set_title('Input', fontsize=12)
        
        axes[1].imshow(y_patch, cmap='viridis')
        axes[1].set_title('Ground Truth', fontsize=12)
        
        # 2. Loop through experiments and dynamically fetch the median model
        for i, (title, exp_name) in enumerate(self.experiments.items()):
            ax = axes[i + 2]
            
            try:
                # Find which model had the median score
                # NOTE: Ensure 'metric_col' and 'model_col' match your exact CSV headers
                median_model_id = self._get_median_model_id(exp_name, metric_col='F1_Score', model_col='Membro do Comitê')
                
                # Construct path: base_exp_dir / out_{exp_name} / {median_model_id} / pred_test.npy
                pred_path = self.base_exp_dir / f'out_{exp_name}' / median_model_id / 'pred_test.npy'
                
                # Load only the specific patch from the median model
                pred_patch = np.load(pred_path, mmap_mode='r')[patch_idx]
                
                ax.imshow(pred_patch, cmap='viridis')
                ax.set_title(title, fontsize=12)
                
            except Exception as e:
                print(f"Skipping '{title}': {e}")
                ax.set_title(f"{title} (Error)", fontsize=12)
                
        # 3. Clean up axes for publication standards
        for ax in axes:
            ax.axis('off')
            
        plt.tight_layout()
        plt.savefig(save_path, dpi=300, bbox_inches='tight', pad_inches=0.05)
        print(f"Figure successfully saved to: {save_path}")
        plt.show()
            
            
