#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Sep  1 15:52:22 2026

@author: rotunno
"""

# %% Imports

import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
from typing import Union
from scipy.stats import mode

# %% Figure Generator

class FigureGenerator:
    """
    Generates publication-quality figure grids dynamically based on the 
    injected dictionary of experiments.
    """
    
    def __init__(self, base_exp_dir: Union[str, Path], master_csv_path: Union[str, Path], experiment_map: dict):
        """
        Args:
            base_exp_dir: The root directory for the experiments.
            master_csv_path: Path to the aggregated CSV summary. 
                             Note: Use strict metrics (0 px relaxation) to calculate median F1 and identify models.
            experiment_map: A dictionary mapping the desired plot title to the specific folder suffix.
        """
        self.base_exp_dir = Path(base_exp_dir)
        
        # Load the master summary generated by CrossExperimentReporter
        self.summary_df = pd.read_csv(master_csv_path)
        
        self.x_path = self.base_exp_dir / 'x_dir' / 'x_test.npy'
        self.y_path = self.base_exp_dir / 'y_dir' / 'y_test.npy'
        
        # The experiments are dynamically injected
        self.experiment_map = experiment_map
        
    def _get_median_patch(self, exp_name: str, patch_idx: int) -> np.ndarray:
        """Fetches the patch from the specific model with the median F1-Score."""
        # 1. Filter data by experiment
        df_exp = self.summary_df[self.summary_df['Experimento'] == exp_name].copy()
        df_models = df_exp[df_exp['Membro'].str.startswith('m_')]
        
        if df_models.empty:
            raise ValueError(f"No individual models found for experiment '{exp_name}'.")
        
        # 2. Sort data by F1
        df_sorted = df_models.sort_values(by='F1').reset_index(drop=True)
        median_model_id = df_sorted.loc[len(df_sorted) // 2, 'Membro']
        
        # 3. Return patch by index
        pred_path = self.base_exp_dir / f'out_{exp_name}' / median_model_id / 'pred_test.npy'
        return np.load(pred_path, mmap_mode='r')[patch_idx]
    
    def _get_ensemble_patch(self, exp_name: str, patch_idx: int, strategy: str) -> np.ndarray:
        """Fetches patches from all 5 models and aggregates them via voting."""
        # 1. Filter data by experiment
        df_exp = self.summary_df[self.summary_df['Experimento'] == exp_name].copy()
        df_models = df_exp[df_exp['Membro'].str.startswith('m_')]
        n_models = len(df_models)
        
        model_preds = []
        exp_dir = self.base_exp_dir / f'out_{exp_name}'
        
        # 2. Load the specific patch from all models
        for i in range(n_models):
            pred_path = exp_dir / f'm_{i}' / 'pred_test.npy' if strategy == 'hard_vote' else exp_dir / f'm_{i}' / 'prob_test.npy'
            if pred_path.exists():
                model_preds.append(np.load(pred_path, mmap_mode='r')[patch_idx])
                
        if not model_preds:
            raise FileNotFoundError(f"No predictions found in {exp_dir}")
            
        stacked_preds = np.array(model_preds) # Shape: (n_models, H, W, 1)
        
        # 3. Return patch depending on the strategy
        if strategy == 'soft_vote':
            mean_prob = np.mean(stacked_preds, axis=0)
            return (mean_prob >= 0.5).astype(np.uint8) # convert to hard predictions via thresholding
        elif strategy == 'hard_vote':
            # keepdims=False prevents mode from adding an extra dimension
            ensemble_pred, _ = mode(stacked_preds, axis=0, keepdims=False)
            return ensemble_pred
        else:
            raise ValueError(f"Unknown ensemble strategy: {strategy}")
            
    def generate_figure(self, patch_idx: int, save_path: Union[str, Path], 
                        strategy: str = 'median', n_rows: int = None, n_cols: int = None):
        """
        Generates the figure using the specified aggregation strategy.
        Valid strategies: 'median', 'soft_vote', 'hard_vote'.
        """
        # Calculate required plots (Input + Ground Truth + 1 for each experiment)
        total_plots = len(self.experiment_map) + 2
        
        # 1. Dynamic Grid Calculation
        if n_rows is None and n_cols is None:
            # Default logic: Use 1 row for small comparisons, 2 rows for larger ones
            n_rows = 2 if total_plots > 4 else 1
            n_cols = math.ceil(total_plots / n_rows)
        elif n_cols is None:
            n_cols = math.ceil(total_plots / n_rows)
        elif n_rows is None:
            n_rows = math.ceil(total_plots / n_cols)
        
        fig, axes = plt.subplots(n_rows, n_cols, figsize=(3 * n_cols, 3.5 * n_rows))
        
        # Flatten axes array for easy sequential access (handles 1D and 2D arrays)
        axes_flat = axes.flatten() if isinstance(axes, np.ndarray) else [axes]
        
        # 2. Load Input and Ground Truth
        x_patch = np.load(self.x_path, mmap_mode='r')[patch_idx].astype(np.float32) # For compatibility with matplotlib
        y_patch = np.load(self.y_path, mmap_mode='r')[patch_idx]
        
        axes_flat[0].imshow(x_patch, cmap='gray')
        axes_flat[0].set_title('Input', fontsize=12)
        
        axes_flat[1].imshow(y_patch, cmap='gray')
        axes_flat[1].set_title('Ground Truth', fontsize=12)
        
        # 3. Iterate through injected experiments
        current_plot_idx = 2
        for title, exp_name in self.experiment_map.items():
            ax = axes_flat[current_plot_idx]
            try:
                # Dispatch to the correct strategy
                if strategy == 'median':
                    pred_patch = self._get_median_patch(exp_name, patch_idx)
                # soft vote or hard vote
                else:
                    pred_patch = self._get_ensemble_patch(exp_name, patch_idx, strategy)
                    
                ax.imshow(pred_patch, cmap='gray')
                ax.set_title(title, fontsize=12)
            except Exception as e:
                print(f"Skipping '{title}': {e}")
                ax.set_title(f"{title} (Error)", fontsize=12)
                
            current_plot_idx += 1
            
        # 4. Clean up axes and hide unused subplots
        for i, ax in enumerate(axes_flat):
            ax.axis('off')
            # Hide empty subplots if the grid has more slots than total_plots
            if i >= total_plots:
                ax.set_visible(False)
        
        # 5. Save and show figure
        plt.tight_layout()
        plt.savefig(save_path, dpi=300, bbox_inches='tight', pad_inches=0.05)
        print(f"Figure successfully saved to: {save_path}")
        plt.show() # Uncomment to plot figure in the window
        plt.close(fig) # Close figure  